fixes pypi release

diff --git a/.github/workflows/pypi.yaml b/.github/workflows/pypi.yaml
--- a/.github/workflows/pypi.yaml
+++ b/.github/workflows/pypi.yaml
@@ -28,12 +28,12 @@ jobs:
         shell: bash
         run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
 
-      - name: "[library] Set fy-core version"
+      - name: "[library] Set version"
         working-directory: library
         shell: bash
         run: poetry version "${{ inputs.FY_VERSION }}"
 
-      - name: "[cli] Set fy-core version"
+      - name: "[cli] Set version"
         working-directory: cli
         shell: bash
         run: poetry version "${{ inputs.FY_VERSION }}"
@@ -52,6 +52,29 @@ jobs:
         working-directory: library
         shell: bash
         run: poetry publish --build
+
+      - name: "[cli] Wait for fy-library version to become available"
+        working-directory: cli
+        shell: bash
+        run: |
+          command="poetry add fy-library==${{ inputs.FY_VERSION }} --dry-run"
+          max_retries=3 
+          retry_interval=1 # Seconds
+
+          for (( i=1; i<=$max_retries; i++ )); do
+            if $command; then
+              echo "Command succeeded!"
+              break
+            else
+              echo "Command failed, retrying in $retry_interval seconds (attempt $i/$max_retries)"
+              sleep $retry_interval
+            fi
+          done
+
+          if [ $i -gt $max_retries ]; then
+            echo "Command failed after $max_retries attempts."
+            exit 1
+          fi
 
       - name: "[cli] Set fy-library version"
         working-directory: cli
